# Generated by Django 5.2.5 on 2025-08-19 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_lesson_course'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pay', models.DateField(auto_now_add=True)),
                ('sum', models.IntegerField()),
                ('method_payment', models.CharField(choices=[('Cash', 'Наличные'), ('Transfer to account', 'Перевод на счет')], max_length=50)),
                ('payment_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.course')),
                ('payment_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'платеж',
                'verbose_name_plural': 'платежи',
            },
        ),
    ]
