# Generated by Django 5.2.5 on 2025-08-23 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_username'),
        ('users', '0003_alter_payment_payment_course_and_more'),
    ]

    operations = [
    ]
