# Generated by Django 5.2.5 on 2025-08-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20250823_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='sa', max_length=50),
        ),
    ]
