# Generated by Django 5.2.5 on 2025-09-06 12:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_recourse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReCourse',
            new_name='Subscription',
        ),
    ]
