# Generated by Django 5.2.5 on 2025-09-06 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_rename_recourse_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='preview',
        ),
    ]
